# Generated by Django 2.2.24 on 2021-09-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('indication_id', models.IntegerField()),
                ('number', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=60)),
                ('created_at', models.DateField()),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
