# Generated by Django 2.2.2 on 2021-09-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_indication_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indication',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
