# Generated by Django 2.2.2 on 2021-09-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_indication'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
