# Generated by Django 2.2.2 on 2021-09-06 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un code postal valide', regex='^[0-9]*$')])),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Veuillez\tentrer\tun numéro de téléphone valide.', regex='^[0-9]*$')])),
                ('date_mise_a_jour', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
